terraform {
  required_version = ">= 1.4.0"

  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "random" {}
provider "local" {}

resource "random_pet" "env" {
  length    = 2
  separator = "-"
}

resource "random_id" "suffix" {
  byte_length = 3
}

locals {
  env_name = var.env_name != null ? var.env_name : random_pet.env.id
  env_id   = "${local.env_name}-${random_id.suffix.hex}"

  out_dir = "${path.module}/out/${local.env_id}"

  services = {
    api     = { port = 8080 }
    worker  = { port = 9000 }
    console = { port = 3000 }
  }

  config = {
    env_id   = local.env_id
    region   = var.region
    features = var.features
    services = local.services
  }
}

resource "local_file" "readme" {
  filename = "${local.out_dir}/README.md"
  content  = <<-EOT
  # ${local.env_id}

  Generated by Terraform.

  - region: ${var.region}
  - features: ${join(", ", var.features)}

  Services:
  ${join("\n", [for name, s in local.services : "- ${name}: ${s.port}"])}
  EOT
}

resource "local_file" "config_json" {
  filename = "${local.out_dir}/config.json"
  content  = jsonencode(local.config)
}

resource "local_file" "service_files" {
  for_each = local.services

  filename = "${local.out_dir}/services/${each.key}.json"
  content  = jsonencode({ name = each.key, port = each.value.port })
}
